import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Add Company | Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='rounded-xl bg-[#F2F2F2]'>
      <div className='h-[calc(100vh-190px)] w-full '>
        <div className='mx-auto flex h-[calc(100vh-190px)] w-[360px] max-w-md items-center justify-center md:min-h-[calc(100vh-133px)]'>
          {children}
        </div>
      </div>
    </div>
  );
}
